import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    emailAddress: 'Correo Electrónico',
    password: 'Contraseña',
    signIn: 'Iniciar Sesión',
    signingIn: 'Iniciando sesión...',
    demoPurposeText: 'Para propósitos de demostración, contacte a su administrador para obtener credenciales de acceso.',
    poweredBySupabase: 'Autenticación segura proporcionada por Supabase',
    dashboard: 'Panel',
    products: 'Productos',
    inventory: 'Inventario',
    orders: 'Pedidos',
    customers: 'Clientes',
    reports: 'Reportes',
    users: 'Usuarios',
    activityLogs: 'Registro de Actividad',
    auditTrail: 'Auditoría',
    signOut: 'Cerrar Sesión',
    addProduct: 'Agregar Producto',
    newProduct: 'Nuevo Producto',
    editProduct: 'Editar Producto',
    stock: 'Stock',
    price: 'Precio',
    recentOrders: 'Pedidos Recientes',
    lowStock: 'Bajo Stock',
    totalProducts: 'Total Productos',
    totalOrders: 'Total Pedidos',
    inventoryValue: 'Valor del Inventario',
    lowStockAlert: 'Alerta de Stock Bajo',
    totalCustomers: 'Total Clientes',
    pendingOrders: 'Pedidos Pendientes',
    systemStatus: 'Estado del Sistema',
    allSystemsOperational: 'Todos los sistemas operativos',
    connectedToDatabase: 'Conectado a la base de datos',
    poweredBy: 'Desarrollado por AUTOPILOTAI',
    welcomeTo: 'Bienvenido a Vitapoint Skincare Inventory',
    inventoryOverview: 'Resumen de Inventario',
    productName: 'Nombre del Producto',
    brand: 'Marca',
    category: 'Categoría',
    sku: 'SKU',
    quantity: 'Cantidad',
    minStockLevel: 'Nivel Mínimo de Stock',
    description: 'Descripción',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    search: 'Buscar',
    searchProducts: 'Buscar por nombre, marca, categoría o SKU...',
    searchOrders: 'Buscar pedidos por cliente o número de pedido...',
    searchInventory: 'Buscar inventario por nombre, marca, categoría o SKU...',
    noProductsFound: 'No se encontraron productos',
    noOrdersFound: 'No se encontraron pedidos',
    tryAdjustingSearch: 'Intente ajustar su búsqueda',
    addFirstProduct: 'Agregue su primer producto para comenzar',
    createProduct: 'Crear Producto',
    manageProducts: 'Gestionar su catálogo de productos de cuidado de la piel',
    updateProductDetails: 'Actualizar detalles del producto',
    addNewProductToCatalog: 'Agregar un nuevo producto a su catálogo',
    productNameRequired: 'Nombre del Producto *',
    brandRequired: 'Marca *',
    categoryRequired: 'Categoría *',
    skuRequired: 'SKU *',
    priceRequired: 'Precio *',
    stockQuantityRequired: 'Cantidad en Stock *',
    minStockLevelRequired: 'Nivel Mínimo de Stock *',
    productDescription: 'Descripción del producto y detalles...',
    saving: 'Guardando...',
    updateProduct: 'Actualizar Producto',
    newOrder: 'Nuevo Pedido',
    editOrder: 'Editar Pedido',
    customerName: 'Nombre del Cliente',
    orderNumber: 'Número de Pedido',
    totalAmount: 'Monto Total',
    status: 'Estado',
    paymentStatus: 'Estado de Pago',
    notes: 'Notas',
    date: 'Fecha',
    total: 'Total',
    pending: 'Pendiente',
    processing: 'Procesando',
    shipped: 'Enviado',
    delivered: 'Entregado',
    cancelled: 'Cancelado',
    unpaid: 'Sin Pagar',
    paid: 'Pagado',
    refunded: 'Reembolsado',
    createOrder: 'Crear Pedido',
    updateOrder: 'Actualizar Pedido',
    manageCustomerOrders: 'Gestionar pedidos de clientes y envíos',
    updateOrderDetails: 'Actualizar detalles del pedido',
    createNewCustomerOrder: 'Crear un nuevo pedido de cliente',
    customerNameRequired: 'Nombre del Cliente *',
    totalAmountRequired: 'Monto Total *',
    statusRequired: 'Estado *',
    paymentStatusRequired: 'Estado de Pago *',
    orderNotes: 'Notas del pedido o instrucciones especiales...',
    inventoryManagement: 'Gestión de Inventario',
    trackAndMonitorStock: 'Rastrear y monitorear niveles de stock de productos',
    totalStockUnits: 'Total Unidades en Stock',
    lowStockItems: 'Artículos con Stock Bajo',
    allProducts: 'Todos los Productos',
    inStock: 'En Stock',
    stockLevel: 'Nivel de Stock',
    units: 'unidades',
    minLevel: 'Nivel mín',
    stockValue: 'Valor de Stock',
    recentInventoryActivity: 'Actividad Reciente del Inventario',
    unknownProduct: 'Producto Desconocido',
    stockAdded: 'Stock agregado',
    stockRemoved: 'Stock removido',
    stockAdjusted: 'Stock ajustado',
    inventorySummary: 'Resumen de Inventario',
    totalUnits: 'Total Unidades',
    inventoryUpdatedRealTime: 'Inventario actualizado en tiempo real',
    reportsAndAnalytics: 'Reportes y Análisis',
    comprehensiveInsights: 'Información completa y métricas de rendimiento',
    totalRevenue: 'Ingresos Totales',
    allTimeSales: 'Ventas de todos los tiempos',
    processingOrders: 'Pedidos en Proceso',
    salesAndRevenue: 'Ventas e Ingresos',
    orderStatus: 'Estado de Pedidos',
    inventoryMovementTrends: 'Tendencias de Movimiento de Inventario',
    lowStockAlertProducts: 'Alerta de Stock Bajo',
    allStockLevelsHealthy: 'Todos los Niveles de Stock Saludables',
    noItemsBelowMinimum: 'No hay artículos por debajo del umbral mínimo',
    current: 'Actual',
    min: 'Mín',
    summaryReport: 'Reporte Resumido',
    activeOrders: 'Pedidos Activos',
    fulfillmentRate: 'Tasa de Cumplimiento',
    reportsUpdatedRealTime: 'Reportes actualizados en tiempo real',
    lastSixMonths: 'Rendimiento de ventas e ingresos de los últimos 6 meses',
    lastFourteenDays: 'Últimos 14 días de movimientos de inventario',
    userManagement: 'Gestión de Usuarios',
    onlyAdministrators: 'Solo los administradores pueden acceder a esta sección.',
    accessDenied: 'Acceso Denegado',
    name: 'Nombre',
    email: 'Email',
    role: 'Rol',
    joined: 'Unido',
    admin: 'Administrador',
    sales: 'Ventas',
    warehouse: 'Almacén',
    noUsersFound: 'No se encontraron usuarios',
    activityLogsTitle: 'Registro de Actividad',
    filters: 'Filtros',
    action: 'Acción',
    entityType: 'Tipo de Entidad',
    allActions: 'Todas las Acciones',
    allTypes: 'Todos los Tipos',
    entity: 'Entidad',
    details: 'Detalles',
    time: 'Hora',
    created: 'Creado',
    updated: 'Actualizado',
    deleted: 'Eliminado',
    viewed: 'Visto',
    roleChanged: 'Rol Cambiado',
    login: 'Inicio de Sesión',
    logout: 'Cierre de Sesión',
    noActivityLogsFound: 'No se encontraron registros de actividad',
    auditTrailTitle: 'Auditoría',
    onlyAdministratorsAudit: 'Solo los administradores pueden ver el registro de auditoría.',
    table: 'Tabla',
    operation: 'Operación',
    allTables: 'Todas las Tablas',
    allOperations: 'Todas las Operaciones',
    before: 'Antes',
    after: 'Después',
    newValues: 'Nuevos Valores',
    oldValues: 'Valores Antiguos',
    noChangesRecorded: 'No se registraron cambios',
    noAuditEntriesFound: 'No se encontraron entradas de auditoría',
    loading: 'Cargando...',
    stockIn: 'Entrada de Stock',
    stockOut: 'Salida de Stock',
    orders2: 'Pedidos',
    revenue: 'Ingresos',
    low: 'Bajo',
    of: 'de',
    ofInventory: 'del inventario',
    delivered2: 'entregados',
    other: 'Otro',
    product: 'producto',
    belowMinimumStock: 'por debajo del nivel mínimo de stock',
    deleteProductConfirm: '¿Está seguro de que desea eliminar este producto?',
    failedToDeleteProduct: 'Error al eliminar el producto',
    failedToSaveProduct: 'Error al guardar el producto. Por favor, inténtelo de nuevo.',
    deleteOrderConfirm: '¿Está seguro de que desea eliminar este pedido?',
    failedToDeleteOrder: 'Error al eliminar el pedido',
    failedToSaveOrder: 'Error al guardar el pedido. Por favor, inténtelo de nuevo.',
    failedToSaveRole: 'Error al guardar el rol',
    productNamePlaceholder: 'ej., Suero de Vitamina C',
    brandPlaceholder: 'ej., CeraVe, The Ordinary',
    categoryPlaceholder: 'ej., Suero, Hidratante, Limpiador',
    skuPlaceholder: 'ej., SKN-001',
    noMatchingFilter: 'No hay productos que coincidan con el filtro seleccionado',
    unknownProductText: 'Producto Desconocido',
    totalOrdersText: 'Total de Pedidos',
    totalRevenueText: 'Ingresos Totales',
    allTimeSalesText: 'Ventas de todos los tiempos',
    processingText: 'Procesando',
    pendingText: 'pendientes',
    lowStockItemsText: 'Artículos con Stock Bajo',
    ofInventoryText: 'del inventario',
    salesRevenue: 'Ventas e Ingresos',
    orderStatusText: 'Estado de Pedidos',
    inventoryMovementText: 'Tendencias de Movimiento de Inventario',
    lowStockAlertText: 'Alerta de Stock Bajo',
    allStockHealthy: 'Todos los Niveles de Stock Saludables',
    noBelowThreshold: 'No hay artículos por debajo del umbral mínimo',
    currentText: 'Actual',
    minText: 'Mín',
    summaryReportText: 'Reporte Resumido',
    totalProductsText: 'Total Productos',
    totalStockValueText: 'Valor Total de Stock',
    activeOrdersText: 'Pedidos Activos',
    fulfillmentRateText: 'Tasa de Cumplimiento',
    reportsUpdatedText: 'Reportes actualizados en tiempo real',
    lastSixMonthsText: 'Rendimiento de ventas e ingresos de los últimos 6 meses',
    lastFourteenDaysText: 'Últimos 14 días de movimientos de inventario',
    lowText: 'Bajo',
    deliveredText: 'entregados',
  },
  en: {
    emailAddress: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    demoPurposeText: 'For demo purposes, please contact your administrator for login credentials.',
    poweredBySupabase: 'Secure authentication powered by Supabase',
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    orders: 'Orders',
    customers: 'Customers',
    reports: 'Reports',
    users: 'Users',
    activityLogs: 'Activity Logs',
    auditTrail: 'Audit Trail',
    signOut: 'Sign Out',
    addProduct: 'Add Product',
    newProduct: 'New Product',
    editProduct: 'Edit Product',
    stock: 'Stock',
    price: 'Price',
    recentOrders: 'Recent Orders',
    lowStock: 'Low Stock',
    totalProducts: 'Total Products',
    totalOrders: 'Total Orders',
    inventoryValue: 'Inventory Value',
    lowStockAlert: 'Low Stock Alert',
    totalCustomers: 'Total Customers',
    pendingOrders: 'Pending Orders',
    systemStatus: 'System Status',
    allSystemsOperational: 'All systems operational',
    connectedToDatabase: 'Connected to database',
    poweredBy: 'Powered by AUTOPILOTAI',
    welcomeTo: 'Welcome to Vitapoint Skincare Inventory',
    inventoryOverview: 'Inventory Overview',
    productName: 'Product Name',
    brand: 'Brand',
    category: 'Category',
    sku: 'SKU',
    quantity: 'Quantity',
    minStockLevel: 'Minimum Stock Level',
    description: 'Description',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    searchProducts: 'Search by name, brand, category, or SKU...',
    searchOrders: 'Search orders by customer or order number...',
    searchInventory: 'Search inventory by name, brand, category, or SKU...',
    noProductsFound: 'No products found',
    noOrdersFound: 'No orders found',
    tryAdjustingSearch: 'Try adjusting your search',
    addFirstProduct: 'Add your first product to get started',
    createProduct: 'Create Product',
    manageProducts: 'Manage your skincare product catalog',
    updateProductDetails: 'Update product details',
    addNewProductToCatalog: 'Add a new product to your catalog',
    productNameRequired: 'Product Name *',
    brandRequired: 'Brand *',
    categoryRequired: 'Category *',
    skuRequired: 'SKU *',
    priceRequired: 'Price *',
    stockQuantityRequired: 'Stock Quantity *',
    minStockLevelRequired: 'Minimum Stock Level *',
    productDescription: 'Product description and details...',
    saving: 'Saving...',
    updateProduct: 'Update Product',
    newOrder: 'New Order',
    editOrder: 'Edit Order',
    customerName: 'Customer Name',
    orderNumber: 'Order Number',
    totalAmount: 'Total Amount',
    status: 'Status',
    paymentStatus: 'Payment Status',
    notes: 'Notes',
    date: 'Date',
    total: 'Total',
    pending: 'Pending',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    unpaid: 'Unpaid',
    paid: 'Paid',
    refunded: 'Refunded',
    createOrder: 'Create Order',
    updateOrder: 'Update Order',
    manageCustomerOrders: 'Manage customer orders and shipping',
    updateOrderDetails: 'Update order details',
    createNewCustomerOrder: 'Create a new customer order',
    customerNameRequired: 'Customer Name *',
    totalAmountRequired: 'Total Amount *',
    statusRequired: 'Status *',
    paymentStatusRequired: 'Payment Status *',
    orderNotes: 'Order notes or special instructions...',
    inventoryManagement: 'Inventory Management',
    trackAndMonitorStock: 'Track and monitor product stock levels',
    totalStockUnits: 'Total Stock Units',
    lowStockItems: 'Low Stock Items',
    allProducts: 'All Products',
    inStock: 'In Stock',
    stockLevel: 'Stock Level',
    units: 'units',
    minLevel: 'Min level',
    stockValue: 'Stock Value',
    recentInventoryActivity: 'Recent Inventory Activity',
    unknownProduct: 'Unknown Product',
    stockAdded: 'Stock added',
    stockRemoved: 'Stock removed',
    stockAdjusted: 'Stock adjusted',
    inventorySummary: 'Inventory Summary',
    totalUnits: 'Total Units',
    inventoryUpdatedRealTime: 'Inventory updated in real-time',
    reportsAndAnalytics: 'Reports & Analytics',
    comprehensiveInsights: 'Comprehensive insights and performance metrics',
    totalRevenue: 'Total Revenue',
    allTimeSales: 'All time sales',
    processingOrders: 'Processing',
    salesAndRevenue: 'Sales & Revenue',
    orderStatus: 'Order Status',
    inventoryMovementTrends: 'Inventory Movement Trends',
    lowStockAlertProducts: 'Low Stock Alert',
    allStockLevelsHealthy: 'All Stock Levels Healthy',
    noItemsBelowMinimum: 'No items below minimum threshold',
    current: 'Current',
    min: 'Min',
    summaryReport: 'Summary Report',
    activeOrders: 'Active Orders',
    fulfillmentRate: 'Fulfillment Rate',
    reportsUpdatedRealTime: 'Reports updated in real-time',
    lastSixMonths: 'Last 6 months sales and revenue performance',
    lastFourteenDays: 'Last 14 days of inventory movements',
    userManagement: 'User Management',
    onlyAdministrators: 'Only administrators can access this section.',
    accessDenied: 'Access Denied',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    joined: 'Joined',
    admin: 'Admin',
    sales: 'Sales',
    warehouse: 'Warehouse',
    noUsersFound: 'No users found',
    activityLogsTitle: 'Activity Logs',
    filters: 'Filters',
    action: 'Action',
    entityType: 'Entity Type',
    allActions: 'All Actions',
    allTypes: 'All Types',
    entity: 'Entity',
    details: 'Details',
    time: 'Time',
    created: 'Created',
    updated: 'Updated',
    deleted: 'Deleted',
    viewed: 'Viewed',
    roleChanged: 'Role Changed',
    login: 'Login',
    logout: 'Logout',
    noActivityLogsFound: 'No activity logs found',
    auditTrailTitle: 'Audit Trail',
    onlyAdministratorsAudit: 'Only administrators can view the audit trail.',
    table: 'Table',
    operation: 'Operation',
    allTables: 'All Tables',
    allOperations: 'All Operations',
    before: 'Before',
    after: 'After',
    newValues: 'New Values',
    oldValues: 'Old Values',
    noChangesRecorded: 'No changes recorded',
    noAuditEntriesFound: 'No audit trail entries found',
    loading: 'Loading...',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    orders2: 'Orders',
    revenue: 'Revenue',
    low: 'Low',
    of: 'of',
    ofInventory: 'of inventory',
    delivered2: 'delivered',
    other: 'Other',
    product: 'product',
    belowMinimumStock: 'below minimum stock level',
    deleteProductConfirm: 'Are you sure you want to delete this product?',
    failedToDeleteProduct: 'Failed to delete product',
    failedToSaveProduct: 'Failed to save product. Please try again.',
    deleteOrderConfirm: 'Are you sure you want to delete this order?',
    failedToDeleteOrder: 'Failed to delete order',
    failedToSaveOrder: 'Failed to save order. Please try again.',
    failedToSaveRole: 'Failed to save role',
    productNamePlaceholder: 'e.g., Vitamin C Serum',
    brandPlaceholder: 'e.g., CeraVe, The Ordinary',
    categoryPlaceholder: 'e.g., Serum, Moisturizer, Cleanser',
    skuPlaceholder: 'e.g., SKN-001',
    noMatchingFilter: 'No products match the selected filter',
    unknownProductText: 'Unknown Product',
    totalOrdersText: 'Total Orders',
    totalRevenueText: 'Total Revenue',
    allTimeSalesText: 'All time sales',
    processingText: 'Processing',
    pendingText: 'pending',
    lowStockItemsText: 'Low Stock Items',
    ofInventoryText: 'of inventory',
    salesRevenue: 'Sales & Revenue',
    orderStatusText: 'Order Status',
    inventoryMovementText: 'Inventory Movement Trends',
    lowStockAlertText: 'Low Stock Alert',
    allStockHealthy: 'All Stock Levels Healthy',
    noBelowThreshold: 'No items below minimum threshold',
    currentText: 'Current',
    minText: 'Min',
    summaryReportText: 'Summary Report',
    totalProductsText: 'Total Products',
    totalStockValueText: 'Total Stock Value',
    activeOrdersText: 'Active Orders',
    fulfillmentRateText: 'Fulfillment Rate',
    reportsUpdatedText: 'Reports updated in real-time',
    lastSixMonthsText: 'Last 6 months sales and revenue performance',
    lastFourteenDaysText: 'Last 14 days of inventory movements',
    lowText: 'Low',
    deliveredText: 'delivered',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'es';
    const saved = localStorage.getItem('vitapoint-language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('vitapoint-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
